package bo;

public class Cohort {
    private int chId;
    private String chName;

    public Cohort(int clsId, String clsName){
        this.chId = clsId;
        this.chName = clsName;
    }
    public int getChId(){
        return 
    }

    public void setChId(int ChId){
        this.chId = chId;

    }

    public String getName(){
        return chName;
    }
    
    public String getChName (String chName){
        this.chName;
    }

    public String toString(){
        return chName;
    }
}