/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FGC;

import java.awt.Toolkit;
import java.util.Map;
import javax.swing.JInternalFrame;

/**
 *
 * @author vande
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmViewStudents
     */
    FrmLogin frmLogin = new FrmLogin();
    FrmAddStudent frmAddStudent = new FrmAddStudent();
    FrmViewStudents frmViewStudents = new FrmViewStudents(); 
    Map<String, JInternalFrame> forms = new HashMap<>();
    
    public FrmMain() {
        initComponents();
        forms.put("frmLogin", frmLogin);
        forms.put("frmAddStudent", frmAddStudent);
        forms.put("frmViewStudents", frmViewStudents);
        //add the to JDesktop Pane

        forms.values().forEach((frm)->{
            jdpContainer.add(frm);
        });
    };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JDPContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileLogin = new javax.swing.JMenuItem();
        fileLogout = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        mngStudent = new javax.swing.JMenu();
        mngStudentAdd = new javax.swing.JMenuItem();
        mngStudentUpdate = new javax.swing.JMenuItem();
        mngStudentDelete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mngMentorAdd = new javax.swing.JMenuItem();
        mngMentorUpdate = new javax.swing.JMenuItem();
        mngMentorDelete = new javax.swing.JMenuItem();
        manageView = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        viewTables = new javax.swing.JMenu();
        viewStudents = new javax.swing.JMenu();
        viewStudentName_stu = new javax.swing.JCheckBoxMenuItem();
        viewSamID_stu = new javax.swing.JMenuItem();
        viewMentorName_stu = new javax.swing.JCheckBoxMenuItem();
        viewMentorID_stu = new javax.swing.JMenuItem();
        viewStudentMajor_stu = new javax.swing.JCheckBoxMenuItem();
        viewStudentMinor_stu = new javax.swing.JCheckBoxMenuItem();
        viewGPA = new javax.swing.JCheckBoxMenuItem();
        viewMentors = new javax.swing.JMenu();
        viewSamID_men = new javax.swing.JCheckBoxMenuItem();
        viewUsername = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        JDPContainer.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout JDPContainerLayout = new javax.swing.GroupLayout(JDPContainer);
        JDPContainer.setLayout(JDPContainerLayout);
        JDPContainerLayout.setHorizontalGroup(
            JDPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        JDPContainerLayout.setVerticalGroup(
            JDPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        getContentPane().add(JDPContainer, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        fileLogin.setText("Login");
        fileLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLoginActionPerformed(evt);
            }
        });
        menuFile.add(fileLogin);

        fileLogout.setText("Logout");
        fileLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLogoutActionPerformed(evt);
            }
        });
        menuFile.add(fileLogout);

        fileExit.setText("Exit Application");
        menuFile.add(fileExit);

        jMenuBar1.add(menuFile);

        menuManage.setText("Manage");

        mngStudent.setText("Student");

        mngStudentAdd.setText("Add");
        mngStudent.add(mngStudentAdd);

        mngStudentUpdate.setText("Update");
        mngStudent.add(mngStudentUpdate);

        mngStudentDelete.setText("Delete");
        mngStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngStudentDeleteActionPerformed(evt);
            }
        });
        mngStudent.add(mngStudentDelete);

        menuManage.add(mngStudent);

        jMenu2.setText("Mentor");

        mngMentorAdd.setText("Add");
        jMenu2.add(mngMentorAdd);

        mngMentorUpdate.setText("Update");
        jMenu2.add(mngMentorUpdate);

        mngMentorDelete.setText("Delete");
        mngMentorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngMentorDeleteActionPerformed(evt);
            }
        });
        jMenu2.add(mngMentorDelete);

        menuManage.add(jMenu2);

        manageView.setText("View");
        menuManage.add(manageView);

        jMenuBar1.add(menuManage);

        jMenu1.setText("View");

        viewTables.setText("Tables");

        viewStudents.setText("Students");

        viewStudentName_stu.setSelected(true);
        viewStudentName_stu.setText("Student Name");
        viewStudents.add(viewStudentName_stu);

        viewSamID_stu.setText("SamID");
        viewSamID_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSamID_stuActionPerformed(evt);
            }
        });
        viewStudents.add(viewSamID_stu);

        viewMentorName_stu.setSelected(true);
        viewMentorName_stu.setText("Mentor Name");
        viewStudents.add(viewMentorName_stu);

        viewMentorID_stu.setText("Mentor SamID");
        viewMentorID_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMentorID_stuActionPerformed(evt);
            }
        });
        viewStudents.add(viewMentorID_stu);

        viewStudentMajor_stu.setSelected(true);
        viewStudentMajor_stu.setText("Major");
        viewStudents.add(viewStudentMajor_stu);

        viewStudentMinor_stu.setSelected(true);
        viewStudentMinor_stu.setText("Minor");
        viewStudents.add(viewStudentMinor_stu);

        viewGPA.setSelected(true);
        viewGPA.setText("GPA");
        viewStudents.add(viewGPA);

        viewTables.add(viewStudents);

        viewMentors.setText("Mentors");

        viewSamID_men.setSelected(true);
        viewSamID_men.setText("SamID");
        viewMentors.add(viewSamID_men);

        viewUsername.setSelected(true);
        viewUsername.setText("Username");
        viewMentors.add(viewUsername);

        viewTables.add(viewMentors);

        jMenu1.add(viewTables);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void fileLoginActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void fileLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void mngStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void mngMentorDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void viewSamID_stuActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void viewMentorID_stuActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FrmMain frmMain =  new FrmMain();
               frmMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
               frmMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JDesktopPane JDPContainer;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileLogin;
    private javax.swing.JMenuItem fileLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem manageView;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenuItem mngMentorAdd;
    private javax.swing.JMenuItem mngMentorDelete;
    private javax.swing.JMenuItem mngMentorUpdate;
    private javax.swing.JMenu mngStudent;
    private javax.swing.JMenuItem mngStudentAdd;
    private javax.swing.JMenuItem mngStudentDelete;
    private javax.swing.JMenuItem mngStudentUpdate;
    private javax.swing.JCheckBoxMenuItem viewGPA;
    private javax.swing.JMenuItem viewMentorID_stu;
    private javax.swing.JCheckBoxMenuItem viewMentorName_stu;
    private javax.swing.JMenu viewMentors;
    private javax.swing.JCheckBoxMenuItem viewSamID_men;
    private javax.swing.JMenuItem viewSamID_stu;
    private javax.swing.JCheckBoxMenuItem viewStudentMajor_stu;
    private javax.swing.JCheckBoxMenuItem viewStudentMinor_stu;
    private javax.swing.JCheckBoxMenuItem viewStudentName_stu;
    private javax.swing.JMenu viewStudents;
    private javax.swing.JMenu viewTables;
    private javax.swing.JCheckBoxMenuItem viewUsername;
    // End of variables declaration                   
}
